
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 31
#define YY_END_OF_BUFFER 32
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[329] =
    {   0,
        0,    0,    0,    0,    0,    0,   21,   21,   25,   25,
        0,    0,    0,    0,    0,    0,   32,   31,    1,   31,
       31,   31,   31,   31,   31,    1,    1,   21,   21,   21,
       21,   31,    1,    1,   25,   25,   25,   25,   25,   31,
       27,    1,    1,    1,   27,   27,   29,    1,    1,    1,
       29,   29,   30,    0,    0,    0,    0,   10,    0,    0,
       21,   21,   21,   21,   21,    0,   25,   25,   25,   25,
       25,   25,   25,   25,   25,    0,   27,   26,   26,   27,
       27,   29,   28,   28,   29,   29,    0,    0,    0,    0,
        0,    0,    0,   21,    0,   25,    0,    0,    0,   27,

       29,    0,    0,    0,    0,   11,    0,    0,    0,    0,
        0,   21,    0,   25,    0,    0,    0,   27,   29,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   21,   21,   21,   21,    0,   25,   25,
       25,   25,    0,    0,    0,   27,   27,   27,   27,   27,
       29,   29,   29,   29,   29,    0,    0,    0,    0,    0,
        0,    0,   14,   12,    0,    0,    0,    0,    0,    0,
       21,   21,   21,   21,    0,   25,   25,   25,   25,    0,
        0,    0,   27,   27,   27,   27,   27,   29,   29,   29,
       29,   29,    0,    0,    0,    0,    0,    0,    0,    0,

        0,   15,   13,    0,    0,   21,   21,   21,   21,    0,
       25,   25,   25,   25,    0,    0,    0,   27,   27,   27,
       27,   27,   29,   29,   29,   29,   29,    0,    0,    2,
        3,    0,    0,    8,    0,   16,    0,    0,   21,   21,
        2,    3,   20,   25,   25,    2,    3,    0,    0,   22,
       27,   27,    2,    3,   27,   29,   29,    2,    3,   29,
        0,    0,    0,    9,    0,    0,   17,   21,   21,   25,
       25,    0,   24,   27,   27,   27,   29,   29,   29,    0,
        7,    0,   18,    0,   21,    7,   25,    7,   23,   27,
        7,   27,   29,    7,   29,    0,    0,   19,   21,   25,

       27,   27,   29,   29,    4,    0,    4,    4,    4,   27,
        4,   29,    0,   27,   29,    0,    0,   27,   27,   29,
       29,    6,    5,    6,    5,    6,    5,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    1,    6,    7,    8,    1,    1,    1,
        1,    9,    1,    9,   10,   11,   12,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,   13,    7,    7,
       14,    7,    7,    7,   15,   16,   16,   17,   18,   16,
       16,   16,   16,   16,   16,   16,   19,   16,   16,   16,
       16,   20,   16,   16,   16,   16,   16,   16,   16,   16,
        7,    1,   21,    1,    1,    1,   22,   16,   16,   23,

       24,   25,   16,   26,   27,   16,   28,   29,   30,   31,
       32,   16,   16,   33,   16,   34,   35,   16,   16,   16,
       16,   16,   36,    1,   37,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[38] =
    {   0,
        1,    2,    3,    1,    2,    4,    2,    5,    4,    2,
        2,    6,    2,    2,    5,    5,    5,    5,    5,    5,
        2,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    7,    7
    } ;

static const flex_int16_t yy_base[348] =
    {   0,
        0,   13,   26,    0,   50,   71,   92,  129,  166,  203,
      239,  252,  265,  278,    0,    1,  640, 1286, 1286,    0,
      625,  603,  606,  619,    2,   31,  102,  106,  112,  291,
      116,  622,  139,  143,  312,  152,  172,  348,  176,  621,
        0,    0,    5,    7,    0,  614,    0,    0,   17,   34,
        0,  613,    0,  612,  591,  602,  611, 1286,   23,  617,
      186,  190,  213,  217,  368,  589,  223,  227,  285,  297,
      318,  389,    0,  322,  425,  190,    0,   41,   43,    0,
      605,    0,   62,   64,    0,  604,  612,  589,  584,   58,
       77,  140,   67,  334,  588,  354,  574,  578,  585,  601,

      600,  216,  572,  574,   95, 1286,  173,  148,  591,   68,
       92,  445,  571,  480,  565,  576,  567,  242,  255,  574,
      577,  570,  560,  583,  555,  574,  556,  560,  253,  286,
      131,  298,   24,  515,  536,  556,  579,  555,  611,  632,
      652,  675,  552,  547,  549,  550,  553,  546,  535,  557,
      542,  544,  536,  523,  547,  523,  535,  514,  521,  513,
      529,  535, 1286, 1286,  248,  319,  506,  511,    2,  293,
      707,  734,  347,  737,  523,  772,  799,  366,  802,  498,
      500,  520,  499,  511,  490,  499,  491,  484,  494,  474,
      482,  472,  478,  481,  473,  469,  469,  484,    0,  334,

      323, 1286, 1286,  238,  179,  820,  840,  858,  876,  450,
      894,  914,  932,  950,  453,  476,  443,  449,  455,  449,
      445,  446,  443,  446,  440,  437,  435,  429,  434, 1286,
     1286,  421,    0,    0,  368,  376,  113,  329,  968,  384,
      387,  422, 1286,  986,  440,  458,  477,  441,  408, 1286,
      419,  424,    0,    0,  410,  413,  418,    0,    0,  406,
      406,  414,  407,    0,  400,  300,  411, 1004, 1023, 1041,
     1060,  382, 1286,  389,  397,  389,  378,  383,  374,  366,
     1286,  376,  397,  341, 1078,  485, 1096,  513, 1286,  347,
        0,  366,  343,    0,  352,  330,  305,  308, 1114, 1132,

      284,  249,  227,  210, 1286,  220,  533,  556,    0,  199,
        0,  172,  169,  338,  404,  118,  113,   71,   68,   29,
       26, 1286, 1286,    0,    0,    0,    0, 1286, 1168, 1175,
     1182, 1189, 1196, 1203, 1210, 1213, 1219, 1224, 1230, 1237,
     1244, 1251, 1258, 1261, 1264, 1271, 1278
    } ;

static const flex_int16_t yy_def[348] =
    {   0,
      329,  329,  329,    3,  330,  330,  331,  331,  332,  332,
      333,  333,  334,  334,    3,    3,  328,  328,  328,  335,
      328,  328,  328,  336,  328,  328,  337,  337,  328,  337,
      328,  328,  328,  338,  339,  338,  328,  338,  328,  328,
      340,  340,  328,  340,  341,  340,  342,  342,  328,  342,
      343,  342,  335,  328,  328,  328,  336,  328,  344,  328,
      328,  337,  337,  328,  337,  328,  328,  338,  338,  328,
      335,  339,   72,  335,  338,  328,  340,  328,  340,  341,
      340,  342,  328,  342,  343,  342,  328,  328,  328,  344,
      344,  344,  345,  337,  328,  338,  328,  328,  328,  340,

      342,  328,  328,  328,  328,  328,  344,  344,  345,  345,
      345,  337,  328,  338,  328,  328,  328,  340,  342,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  344,  344,
      328,  345,  345,  337,  337,  337,  337,  328,  338,  338,
      338,  338,  328,  328,  328,  340,  340,  340,  340,  340,
      342,  342,  342,  342,  342,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  344,  344,  328,  328,  345,  345,
      337,  337,  112,  112,  328,  338,  338,  114,  114,  328,
      328,  328,  340,  340,  340,  340,  340,  342,  342,  342,
      342,  342,  328,  328,  328,  328,  328,  328,  346,  344,

      344,  328,  328,  345,  345,  112,  112,  112,  112,  328,
      114,  114,  114,  114,  328,  328,  328,  340,  340,  340,
      340,  340,  342,  342,  342,  342,  342,  328,  328,  328,
      328,  328,  347,  346,  344,  344,  345,  345,  112,  112,
      112,  112,  328,  114,  114,  114,  114,  328,  328,  328,
      340,  340,  340,  340,  340,  342,  342,  342,  342,  342,
      328,  328,  328,  347,  344,  345,  345,  112,  112,  114,
      114,  328,  328,  340,  340,  340,  342,  342,  342,  328,
      328,  328,  344,  345,  112,  112,  114,  114,  328,  340,
      340,  340,  342,  342,  342,  328,  328,  345,  112,  114,

      340,  340,  342,  342,  328,  328,  112,  114,  340,  340,
      342,  342,  328,  340,  342,  328,  328,  340,  340,  342,
      342,  328,  328,  340,  340,  342,  342,    0,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328
    } ;

static const flex_int16_t yy_nxt[1324] =
    {   0,
      328,   19,   19,   19,   19,   20,   59,   78,   78,   78,
       79,   60,  131,   21,   19,   19,   19,   19,   20,   83,
       83,   18,   18,   18,   18,  204,   21,   19,   19,   19,
       19,   20,   61,   61,  131,   61,   83,   84,  170,   21,
       61,   91,   92,   78,   78,   78,   79,   22,  327,   23,
       18,   19,   19,   19,   19,   20,   18,  326,   18,   25,
       18,   18,   18,   21,   83,   83,   83,   84,  105,  106,
       18,   18,   19,   19,   19,   19,   20,   18,  131,   18,
       25,   18,   18,   18,   21,  110,  111,  105,  106,  132,
      325,   18,   18,   26,   26,   19,   27,   20,  107,  324,

       18,   29,  131,   61,   61,   30,   62,   61,   61,  133,
       62,   61,   31,   61,   61,   61,   61,   61,   61,  127,
       61,   61,   64,  131,  128,   61,   64,   32,   18,   18,
       26,   26,   19,   27,   20,  323,   64,   18,   29,  266,
       67,   67,   30,   67,   67,   67,  322,   68,   67,   31,
      105,  106,   67,   67,   67,  167,   68,  108,  105,  106,
      168,   67,  130,   70,   32,   18,   18,   33,   33,   19,
       34,   35,   70,   67,   67,   37,   67,   67,   67,   38,
       67,   67,  315,  105,  106,   67,   39,   61,   61,  131,
       61,   61,   61,  316,   62,   61,   70,  238,  317,   61,

      129,   40,   18,   18,   33,   33,   19,   34,   35,  314,
       64,   97,   37,   98,   61,   61,   38,   62,   61,   61,
       99,   61,   61,   39,   67,   67,   61,   67,   67,   67,
      313,   68,   67,   64,  120,  121,   67,   64,   40,   18,
       42,   43,   44,   42,   45,  122,  312,   70,  131,  123,
      311,  124,   46,   42,   43,   44,   42,   45,  105,  106,
      146,  147,  237,  105,  106,   46,   48,   49,   50,   48,
       51,  148,  200,  151,  152,  149,  165,  150,   52,   48,
       49,   50,   48,   51,  153,  310,   67,   67,  154,   68,
      155,   52,   61,   61,   67,   62,  105,  106,   67,   67,

       61,   67,  166,  131,   65,   70,   67,  309,  131,  205,
      131,   64,   53,   71,   67,   53,   72,   70,  131,   71,
       67,   71,   71,   71,   67,  169,   71,   71,  284,  105,
      106,   71,   74,  105,  106,   61,   61,  201,  112,  131,
      236,  306,   74,   61,  105,  106,  267,   53,   53,   67,
       67,  131,   68,  305,   64,   67,   67,   67,  114,  304,
      235,   75,  318,   67,  298,   63,   63,  319,   70,   61,
       61,  303,   62,  302,   70,  301,   63,   61,  105,  106,
      208,   94,  328,  297,   69,   69,  105,  106,   64,   53,
       71,   67,   53,   72,  296,   69,  265,  295,   71,  213,

      294,  328,  269,   63,  293,   63,   63,  105,  106,   74,
      105,  106,  292,   63,  291,  290,   63,   63,  289,  328,
       63,  131,  328,  283,   53,   53,   67,   67,  320,   68,
      282,  281,  280,  321,   67,  279,  278,  277,   96,  276,
       63,   63,  275,  274,  273,   70,   61,   61,  272,   62,
      263,   63,  262,  261,   61,   63,  260,  328,  271,   69,
      259,  258,  257,  134,  135,   64,  256,  255,  254,   69,
      253,  252,  251,   69,  136,  328,   69,   69,  137,  250,
      124,   67,   67,  249,   68,  248,  243,   69,  233,   67,
      232,   69,  231,  328,  230,   69,   69,  229,  139,  140,

       70,  228,  227,   63,   63,  226,   69,  225,  224,  141,
       69,  223,  328,  142,   63,  124,   61,   61,   63,   62,
      328,  222,  221,  220,   61,  219,  218,  217,  216,  215,
      210,   69,   69,  203,  202,   64,  171,   61,   61,  199,
       62,  198,   69,  197,  196,   61,   69,  195,  328,  194,
      193,   63,   63,  172,  192,  191,   64,   61,   61,  190,
       62,  189,   63,  188,  187,   61,   63,  186,  328,  185,
      184,  183,  182,  181,   69,   69,   64,  180,  175,  173,
       61,   61,  164,   62,  163,   69,  162,  161,   61,   69,
      160,  328,  159,  158,  157,  156,  145,  144,  143,   64,

      138,  131,  126,  125,  119,  118,  117,  116,  115,  113,
      104,  174,   67,   67,  103,   68,  102,  101,  100,   95,
       67,   93,   58,   89,   88,   87,   86,   81,   76,   66,
       58,   70,  176,   67,   67,   56,   68,   55,   54,  328,
      328,   67,  328,  328,  328,  328,  328,  328,  328,  177,
      328,  328,   70,   67,   67,  328,   68,  328,  328,  328,
      328,   67,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,   70,  328,  328,  178,   67,   67,  328,   68,
      328,  328,  328,  328,   67,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,   70,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  179,   61,   61,
      328,   62,  328,  328,  328,  328,   61,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,   64,  328,  328,
      328,  328,  328,  328,  206,   61,   61,  328,   62,  328,
      328,  328,  328,   61,  328,  328,  328,  328,  207,  328,
      328,  328,  328,  328,   64,   63,   63,  328,  328,  328,
      209,  328,  328,  328,  328,  328,   63,  328,  328,  328,
       63,  328,  328,   67,   67,  328,   68,  328,  328,  328,
      328,   67,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,   70,  328,  328,  328,  328,  328,  328,  211,

       67,   67,  328,   68,  328,  328,  328,  328,   67,  328,
      328,  328,  328,  212,  328,  328,  328,  328,  328,   70,
       69,   69,  328,  328,  328,  214,  328,  328,  328,  328,
      328,   69,  328,  328,  328,   69,  328,  328,   63,   63,
      328,  328,  328,  239,  328,  328,  328,  328,  328,   63,
      328,  328,  328,   63,  328,  328,  240,  328,   63,   63,
      328,  328,  328,  328,  328,  328,  328,  328,  328,   63,
      328,  328,  328,   63,  328,  328,   63,   63,  328,  241,
      328,  328,  328,  328,  328,  328,  328,   63,  328,  328,
      328,   63,  328,  328,   63,   63,  328,  328,  328,  242,

      328,  328,  328,  328,  328,   63,  328,  328,  328,   63,
      328,  328,   69,   69,  328,  328,  328,  244,  328,  328,
      328,  328,  328,   69,  328,  328,  328,   69,  328,  328,
      245,  328,   69,   69,  328,  328,  328,  328,  328,  328,
      328,  328,  328,   69,  328,  328,  328,   69,  328,  328,
       69,   69,  328,  246,  328,  328,  328,  328,  328,  328,
      328,   69,  328,  328,  328,   69,  328,  328,   69,   69,
      328,  328,  328,  247,  328,  328,  328,  328,  328,   69,
      328,  328,  328,   69,  328,  328,   63,   63,  328,  328,
      328,  328,  268,  328,  328,  328,  328,   63,  328,  328,

      328,   63,  328,  328,   69,   69,  328,  328,  328,  328,
      270,  328,  328,  328,  328,   69,  328,  328,  328,   69,
      328,  328,   63,   63,  328,  328,  328,  328,  328,  328,
      285,  328,  328,   63,  328,  328,  328,   63,  328,  328,
      286,   63,   63,  328,  328,  328,  328,  328,  328,  328,
      328,  328,   63,  328,  328,  328,   63,  328,  328,   69,
       69,  328,  328,  328,  328,  328,  328,  287,  328,  328,
       69,  328,  328,  328,   69,  328,  328,  288,   69,   69,
      328,  328,  328,  328,  328,  328,  328,  328,  328,   69,
      328,  328,  328,   69,  328,  328,   63,   63,  328,  328,

      328,  328,  328,  328,  328,  328,  299,   63,  328,  328,
      328,   63,  328,  328,   69,   69,  328,  328,  328,  328,
      328,  328,  328,  328,  300,   69,  328,  328,  328,   69,
      328,  328,   63,   63,  328,  328,  328,  307,  328,  328,
      328,  328,  328,   63,  328,  328,  328,   63,  328,  328,
       69,   69,  328,  328,  328,  308,  328,  328,  328,  328,
      328,   69,  328,  328,  328,   69,  328,  328,   18,   18,
       18,   18,   18,   18,   18,   24,   24,   24,   24,   24,
       24,   24,   28,   28,   28,   28,   28,   28,   28,   36,
       36,   36,   36,   36,   36,   36,   41,   41,   41,   41,

       41,   41,   41,   47,   47,   47,   47,   47,   47,   47,
       53,   53,  328,   53,   53,   53,   53,   57,   57,   57,
       63,   63,  328,   63,   63,   69,   69,   69,   69,   69,
       73,   73,   73,   73,   73,   73,   73,   77,   77,  328,
       77,   77,   77,   77,   80,   80,  328,   80,   80,   80,
       80,   82,   82,  328,   82,   82,   82,   82,   85,   85,
      328,   85,   85,   85,   85,   90,  328,   90,  109,  328,
      109,  234,  234,  328,  234,  234,  234,  234,  264,  264,
      328,  264,  264,  264,  264,   17,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328
    } ;

static const flex_int16_t yy_chk[1324] =
    {   0,
        0,    1,    1,    1,    1,    1,   25,   43,   43,   44,
       44,   25,  169,    1,    2,    2,    2,    2,    2,   49,
       49,   15,   16,   15,   16,  169,    2,    3,    3,    3,
        3,    3,   26,   26,  133,   26,   50,   50,  133,    3,
       26,   59,   59,   78,   78,   79,   79,    3,  321,    3,
        5,    5,    5,    5,    5,    5,    5,  320,    5,    5,
        5,    5,    5,    5,   83,   83,   84,   84,   90,   90,
        5,    6,    6,    6,    6,    6,    6,    6,  110,    6,
        6,    6,    6,    6,    6,   93,   93,   91,   91,  110,
      319,    6,    7,    7,    7,    7,    7,    7,   91,  318,

        7,    7,  111,   27,   27,    7,   27,   28,   28,  111,
       28,   27,    7,   29,   29,   28,   29,   31,   31,  105,
       31,   29,   27,  237,  105,   31,   28,    7,    7,    8,
        8,    8,    8,    8,    8,  317,   31,    8,    8,  237,
       33,   33,    8,   33,   34,   34,  316,   34,   33,    8,
       92,   92,   34,   36,   36,  131,   36,   92,  108,  108,
      131,   36,  108,   34,    8,    8,    9,    9,    9,    9,
        9,    9,   36,   37,   37,    9,   37,   39,   39,    9,
       39,   37,  312,  107,  107,   39,    9,   61,   61,  205,
       61,   62,   62,  313,   62,   61,   39,  205,  313,   62,

      107,    9,    9,   10,   10,   10,   10,   10,   10,  310,
       62,   76,   10,   76,   63,   63,   10,   63,   64,   64,
       76,   64,   63,   10,   67,   67,   64,   67,   68,   68,
      306,   68,   67,   63,  102,  102,   68,   64,   10,   10,
       11,   11,   11,   11,   11,  102,  304,   68,  204,  102,
      303,  102,   11,   12,   12,   12,   12,   12,  165,  165,
      118,  118,  204,  129,  129,   12,   13,   13,   13,   13,
       13,  118,  165,  119,  119,  118,  129,  118,   13,   14,
       14,   14,   14,   14,  119,  302,   69,   69,  119,   69,
      119,   14,   30,   30,   69,   30,  130,  130,   70,   70,

       30,   70,  130,  170,   30,   69,   70,  301,  132,  170,
      266,   30,   35,   35,   35,   35,   35,   70,  298,   71,
       71,   35,   71,   74,   74,  132,   74,   71,  266,  166,
      166,   74,   35,  201,  201,   94,   94,  166,   94,  238,
      201,  297,   74,   94,  200,  200,  238,   35,   35,   38,
       38,  284,   38,  296,   94,   96,   96,   38,   96,  295,
      200,   38,  314,   96,  284,  173,  173,  314,   38,   65,
       65,  293,   65,  292,   96,  290,  173,   65,  235,  235,
      173,   65,  173,  282,  178,  178,  236,  236,   65,   72,
       72,   72,   72,   72,  280,  178,  235,  279,   72,  178,

      278,  178,  240,  240,  277,  241,  241,  283,  283,   72,
      265,  265,  276,  240,  275,  274,  241,  240,  272,  240,
      241,  267,  241,  265,   72,   72,   75,   75,  315,   75,
      263,  262,  261,  315,   75,  260,  257,  256,   75,  255,
      242,  242,  252,  251,  249,   75,  112,  112,  248,  112,
      232,  242,  229,  228,  112,  242,  227,  242,  245,  245,
      226,  225,  224,  112,  112,  112,  223,  222,  221,  245,
      220,  219,  218,  245,  112,  245,  246,  246,  112,  217,
      112,  114,  114,  216,  114,  215,  210,  246,  198,  114,
      197,  246,  196,  246,  195,  247,  247,  194,  114,  114,

      114,  193,  192,  286,  286,  191,  247,  190,  189,  114,
      247,  188,  247,  114,  286,  114,  134,  134,  286,  134,
      286,  187,  186,  185,  134,  184,  183,  182,  181,  180,
      175,  288,  288,  168,  167,  134,  134,  135,  135,  162,
      135,  161,  288,  160,  159,  135,  288,  158,  288,  157,
      156,  307,  307,  135,  155,  154,  135,  136,  136,  153,
      136,  152,  307,  151,  150,  136,  307,  149,  307,  148,
      147,  146,  145,  144,  308,  308,  136,  143,  138,  136,
      137,  137,  128,  137,  127,  308,  126,  125,  137,  308,
      124,  308,  123,  122,  121,  120,  117,  116,  115,  137,

      113,  109,  104,  103,  101,  100,   99,   98,   97,   95,
       89,  137,  139,  139,   88,  139,   87,   86,   81,   66,
      139,   60,   57,   56,   55,   54,   52,   46,   40,   32,
       24,  139,  139,  140,  140,   23,  140,   22,   21,   17,
        0,  140,    0,    0,    0,    0,    0,    0,    0,  140,
        0,    0,  140,  141,  141,    0,  141,    0,    0,    0,
        0,  141,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  141,    0,    0,  141,  142,  142,    0,  142,
        0,    0,    0,    0,  142,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  142,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,  142,  171,  171,
        0,  171,    0,    0,    0,    0,  171,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  171,    0,    0,
        0,    0,    0,    0,  171,  172,  172,    0,  172,    0,
        0,    0,    0,  172,    0,    0,    0,    0,  172,    0,
        0,    0,    0,    0,  172,  174,  174,    0,    0,    0,
      174,    0,    0,    0,    0,    0,  174,    0,    0,    0,
      174,    0,  174,  176,  176,    0,  176,    0,    0,    0,
        0,  176,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  176,    0,    0,    0,    0,    0,    0,  176,

      177,  177,    0,  177,    0,    0,    0,    0,  177,    0,
        0,    0,    0,  177,    0,    0,    0,    0,    0,  177,
      179,  179,    0,    0,    0,  179,    0,    0,    0,    0,
        0,  179,    0,    0,    0,  179,    0,  179,  206,  206,
        0,    0,    0,  206,    0,    0,    0,    0,    0,  206,
        0,    0,    0,  206,    0,  206,  207,    0,  207,  207,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  207,
        0,    0,    0,  207,    0,  207,  208,  208,    0,  208,
        0,    0,    0,    0,    0,    0,    0,  208,    0,    0,
        0,  208,    0,  208,  209,  209,    0,    0,    0,  209,

        0,    0,    0,    0,    0,  209,    0,    0,    0,  209,
        0,  209,  211,  211,    0,    0,    0,  211,    0,    0,
        0,    0,    0,  211,    0,    0,    0,  211,    0,  211,
      212,    0,  212,  212,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  212,    0,    0,    0,  212,    0,  212,
      213,  213,    0,  213,    0,    0,    0,    0,    0,    0,
        0,  213,    0,    0,    0,  213,    0,  213,  214,  214,
        0,    0,    0,  214,    0,    0,    0,    0,    0,  214,
        0,    0,    0,  214,    0,  214,  239,  239,    0,    0,
        0,    0,  239,    0,    0,    0,    0,  239,    0,    0,

        0,  239,    0,  239,  244,  244,    0,    0,    0,    0,
      244,    0,    0,    0,    0,  244,    0,    0,    0,  244,
        0,  244,  268,  268,    0,    0,    0,    0,    0,    0,
      268,    0,    0,  268,    0,    0,    0,  268,    0,  268,
      269,  269,  269,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  269,    0,    0,    0,  269,    0,  269,  270,
      270,    0,    0,    0,    0,    0,    0,  270,    0,    0,
      270,    0,    0,    0,  270,    0,  270,  271,  271,  271,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  271,
        0,    0,    0,  271,    0,  271,  285,  285,    0,    0,

        0,    0,    0,    0,    0,    0,  285,  285,    0,    0,
        0,  285,    0,  285,  287,  287,    0,    0,    0,    0,
        0,    0,    0,    0,  287,  287,    0,    0,    0,  287,
        0,  287,  299,  299,    0,    0,    0,  299,    0,    0,
        0,    0,    0,  299,    0,    0,    0,  299,    0,  299,
      300,  300,    0,    0,    0,  300,    0,    0,    0,    0,
        0,  300,    0,    0,    0,  300,    0,  300,  329,  329,
      329,  329,  329,  329,  329,  330,  330,  330,  330,  330,
      330,  330,  331,  331,  331,  331,  331,  331,  331,  332,
      332,  332,  332,  332,  332,  332,  333,  333,  333,  333,

      333,  333,  333,  334,  334,  334,  334,  334,  334,  334,
      335,  335,    0,  335,  335,  335,  335,  336,  336,  336,
      337,  337,    0,  337,  337,  338,  338,  338,  338,  338,
      339,  339,  339,  339,  339,  339,  339,  340,  340,    0,
      340,  340,  340,  340,  341,  341,    0,  341,  341,  341,
      341,  342,  342,    0,  342,  342,  342,  342,  343,  343,
        0,  343,  343,  343,  343,  344,    0,  344,  345,    0,
      345,  346,  346,    0,  346,  346,  346,  346,  347,  347,
        0,  347,  347,  347,  347,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "reader.l"
#line 2 "reader.l"
#include <stdio.h>
#include <string.h>
#include "file.h"

char* name, *namefol;
File fol;
char* author, * email;
char* filename;
char* make = "", *readme = "", *flStr = "";
char* mdStr = "";
File subfol;
File file;

char* myCat (char* original, char* apendice){
  char* new_str;
  if((new_str = malloc(strlen(original)+strlen(apendice)+1)) != NULL){
    new_str[0] = '\0';
    strcat(new_str,original);
    strcat(new_str,apendice);
  } 
  return new_str;
}

void mkMakeFile(char* str){
    FILE* mk;
    mk = fopen("Makefile", "w");
    for (int i = 0; str[i] != '\0'; i++) {
            fputc(str[i], mk);
        }
    fclose(mk);
}

void mkMD(char* str){
    FILE* md;
    char* file_name = "";
    file_name = myCat (file_name, name);
    file_name = myCat (file_name, ".md");
    md = fopen(file_name, "w");
    for (int i = 0; str[i] != '\0'; i++) {
            fputc(str[i], md);
        }
    fclose(md);
}

void mkFL(char* str){
    FILE* fl;
    char* file_name = "";
    file_name = myCat (file_name, name);
    file_name = myCat (file_name, ".fl");
    fl = fopen(file_name, "w");
    for (int i = 0; str[i] != '\0'; i++) {
            fputc(str[i], fl);
        }
    fclose(fl);
}

void mkREADME(char* str){
    FILE* readme;
    char* file_name = "README.md";
    readme = fopen(file_name, "w");
    for (int i = 0; str[i] != '\0'; i++) {
            fputc(str[i], readme);
        }
    fclose(readme);
}


#line 914 "lex.yy.c"

#line 916 "lex.yy.c"

#define INITIAL 0
#define META 1
#define TREE 2
#define MAKEFILE 3
#define MD 4
#define FL 5
#define README 6
#define NAME 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 73 "reader.l"

#line 75 "reader.l"
    
    BEGIN 0; 

  

#line 1148 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 329 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1286 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 80 "reader.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 81 "reader.l"
{ BEGIN META; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 83 "reader.l"
{ BEGIN TREE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 85 "reader.l"
{ BEGIN MAKEFILE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 87 "reader.l"
{ BEGIN MD; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 89 "reader.l"
{ BEGIN FL; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 91 "reader.l"
{ BEGIN README; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 93 "reader.l"
{email = strdup(yytext+7);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 94 "reader.l"
{author = strdup(yytext+8);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 97 "reader.l"
{   
  
                    fol=initFile(); 
                    if(!strcmp(yytext, "{%name%}/")) setName(fol, namefol);
                    else setName(fol, yytext);
                   }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 104 "reader.l"
{
                      subfol=initFile();
                      if(!strcmp(yytext+2, "{%name%}/")) setName(subfol, namefol);
                      else setName(subfol, yytext+2);
                      push(fol, subfol);
                    }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 111 "reader.l"
{
                        file=initFile();
                        if(!strcmp(yytext+2, "{%name%}.md")) setName(file, myCat(name, ".md"));
                        else setName(file, yytext+2);
                        push(fol, file);
                      }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 118 "reader.l"
{
                        file=initFile();
                        if(!strcmp(yytext+3, "{%name%}.md")) setName(file, myCat(name, ".md"));
                        else setName(file, yytext+2);
                        push(subfol, file);
                      }   
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 125 "reader.l"
{
                        file=initFile();
                        if(!strcmp(yytext+2, "{%name%}.fl")) setName(file, myCat(name, ".fl"));
                        else setName(file, yytext+2);
                        push(fol, file);
                      }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 132 "reader.l"
{
                        file=initFile();
                        if(!strcmp(yytext+3, "{%name%}.fl")) setName(file, myCat(name, ".fl"));
                        else setName(file, yytext+2);
                        push(subfol, file);
                      }                     
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 140 "reader.l"
{
                      file=initFile();
                      setName(file, "README");
                      push(fol, file);
                    }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 146 "reader.l"
{
                      file=initFile();
                      setName(file, "README");
                      push(subfol, file);
                    }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 153 "reader.l"
{ 
                      file=initFile();
                      setName(file, "Makefile");
                      push(fol, file);
                    }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 159 "reader.l"
{
                      file=initFile();
                      setName(file, "Makefile");
                      push(subfol, file);
                    }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 166 "reader.l"
{ make=myCat(make,name); }
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 167 "reader.l"
{ make=myCat(make,yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 171 "reader.l"
{ mdStr=myCat(mdStr, name); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 172 "reader.l"
{ mdStr=myCat(mdStr, author); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 173 "reader.l"
{ mdStr=myCat(mdStr, email); }
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 174 "reader.l"
{ mdStr=myCat(mdStr, yytext); }
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 176 "reader.l"
{ flStr=myCat(flStr, "\n"); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 177 "reader.l"
{ flStr=myCat(flStr, yytext); }
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 179 "reader.l"
{ readme=myCat(readme, "\n"); printf("what\n"); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 180 "reader.l"
{ readme=myCat(readme, yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 182 "reader.l"
;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 185 "reader.l"
ECHO;
	YY_BREAK
#line 1411 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(META):
case YY_STATE_EOF(TREE):
case YY_STATE_EOF(MAKEFILE):
case YY_STATE_EOF(MD):
case YY_STATE_EOF(FL):
case YY_STATE_EOF(README):
case YY_STATE_EOF(NAME):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 329 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 329 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 328);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 185 "reader.l"




int main(int argc, char** argv){
  name = strdup(argv[1]);
  namefol = strdup(argv[1]);
  strcat(namefol , "/");

  yylex();
  mkMakeFile(make);
  mkMD(mdStr);
  mkFL(flStr);
  mkREADME(readme);

  freeFile(fol);


  return 0;
}
